"""
Report Generator Module
Generates security audit reports for SQL injection vulnerabilities
"""

from datetime import datetime
from typing import List, Dict
import json
import os


class ReportGenerator:
    """Generates structured security audit reports"""

    def __init__(self, output_dir: str = 'reports'):
        """
        Initialize ReportGenerator

        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_markdown_report(self, scan_results: Dict, output_file: str = None) -> str:
        """
        Generate Markdown security audit report

        Args:
            scan_results: Dictionary containing scan results
            output_file: Output filename (optional)

        Returns:
            Path to generated report file
        """
        if not output_file:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_file = f'security_audit_report_{timestamp}.md'

        report_path = os.path.join(self.output_dir, output_file)

        with open(report_path, 'w', encoding='utf-8') as f:
            # Header
            f.write("# SQL Injection Security Audit Report\n\n")
            f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            f.write("---\n\n")

            # Executive Summary
            f.write("## Executive Summary\n\n")
            f.write(self._generate_executive_summary(scan_results))
            f.write("\n---\n\n")

            # Scan Details
            f.write("## Scan Details\n\n")
            f.write(self._generate_scan_details(scan_results))
            f.write("\n---\n\n")

            # Vulnerability Findings
            f.write("## Vulnerability Findings\n\n")
            f.write(self._generate_vulnerability_findings(scan_results))
            f.write("\n---\n\n")

            # OWASP Mapping
            f.write("## OWASP Top 10 Mapping\n\n")
            f.write(self._generate_owasp_mapping(scan_results))
            f.write("\n---\n\n")

            # Remediation Recommendations
            f.write("## Remediation Recommendations\n\n")
            f.write(self._generate_remediation_recommendations(scan_results))
            f.write("\n---\n\n")

            # Detailed Findings
            f.write("## Detailed Findings\n\n")
            f.write(self._generate_detailed_findings(scan_results))
            f.write("\n---\n\n")

            # Footer
            f.write("## Disclaimer\n\n")
            f.write("This report is for educational and authorized security testing purposes only. ")
            f.write("Unauthorized testing of web applications is illegal.\n\n")
            f.write("---\n")
            f.write("*Report generated by SQL Injection Analyser*\n")

        return report_path

    def _generate_executive_summary(self, scan_results: Dict) -> str:
        """Generate executive summary section"""
        vulnerabilities = scan_results.get('vulnerabilities', [])
        total_tests = scan_results.get('total_tests', 0)
        total_vulns = len([v for v in vulnerabilities if v.get('is_vulnerable')])

        # Count by severity
        critical = len([v for v in vulnerabilities if v.get('severity') == 'CRITICAL'])
        high = len([v for v in vulnerabilities if v.get('severity') == 'HIGH'])
        medium = len([v for v in vulnerabilities if v.get('severity') == 'MEDIUM'])
        low = len([v for v in vulnerabilities if v.get('severity') == 'LOW'])

        summary = f"**Target URL:** {scan_results.get('target_url', 'N/A')}\n\n"
        summary += f"**Total Tests Performed:** {total_tests}\n\n"
        summary += f"**Vulnerabilities Found:** {total_vulns}\n\n"

        summary += "### Severity Breakdown\n\n"
        summary += f"- 🔴 **Critical:** {critical}\n"
        summary += f"- 🟠 **High:** {high}\n"
        summary += f"- 🟡 **Medium:** {medium}\n"
        summary += f"- 🟢 **Low:** {low}\n\n"

        if critical > 0:
            summary += "⚠️ **CRITICAL VULNERABILITIES DETECTED** - Immediate action required!\n\n"
        elif high > 0:
            summary += "⚠️ **HIGH SEVERITY VULNERABILITIES DETECTED** - Prompt remediation recommended.\n\n"
        elif total_vulns > 0:
            summary += "ℹ️ Vulnerabilities detected - Review and remediate as appropriate.\n\n"
        else:
            summary += "✅ No SQL injection vulnerabilities detected.\n\n"

        return summary

    def _generate_scan_details(self, scan_results: Dict) -> str:
        """Generate scan details section"""
        details = f"- **Scan Start Time:** {scan_results.get('start_time', 'N/A')}\n"
        details += f"- **Scan End Time:** {scan_results.get('end_time', 'N/A')}\n"
        details += f"- **Duration:** {scan_results.get('duration', 'N/A')}\n"
        details += f"- **Target URL:** {scan_results.get('target_url', 'N/A')}\n"
        details += f"- **Injection Points Tested:** {len(scan_results.get('injection_points', []))}\n"
        details += f"- **Payloads Used:** {scan_results.get('total_payloads', 0)}\n\n"

        return details

    def _generate_vulnerability_findings(self, scan_results: Dict) -> str:
        """Generate vulnerability findings summary"""
        vulnerabilities = [v for v in scan_results.get('vulnerabilities', []) if v.get('is_vulnerable')]

        if not vulnerabilities:
            return "✅ **No vulnerabilities found.**\n\n"

        findings = f"**Total Vulnerabilities:** {len(vulnerabilities)}\n\n"

        # Group by type
        vuln_by_type = {}
        for vuln in vulnerabilities:
            vuln_type = vuln.get('vulnerability_type', 'Unknown')
            if vuln_type not in vuln_by_type:
                vuln_by_type[vuln_type] = []
            vuln_by_type[vuln_type].append(vuln)

        findings += "### Vulnerabilities by Type\n\n"
        for vuln_type, vulns in vuln_by_type.items():
            findings += f"#### {vuln_type}\n\n"
            findings += f"**Count:** {len(vulns)}\n\n"
            for vuln in vulns:
                findings += f"- **Parameter:** `{vuln.get('parameter', 'N/A')}`\n"
                findings += f"  - **Method:** {vuln.get('method', 'N/A')}\n"
                findings += f"  - **Severity:** {vuln.get('severity', 'N/A')}\n"
                findings += f"  - **Confidence:** {vuln.get('confidence', 'N/A')}\n\n"

        return findings

    def _generate_owasp_mapping(self, scan_results: Dict) -> str:
        """Generate OWASP Top 10 mapping"""
        mapping = "SQL Injection vulnerabilities map to:\n\n"
        mapping += "### OWASP Top 10 2021: A03:2021 – Injection\n\n"
        mapping += "**Description:** Injection flaws, such as SQL, NoSQL, OS, and LDAP injection, "
        mapping += "occur when untrusted data is sent to an interpreter as part of a command or query.\n\n"

        mapping += "**Risk Factors:**\n"
        mapping += "- **Prevalence:** Common\n"
        mapping += "- **Detectability:** Easy\n"
        mapping += "- **Impact:** Severe\n\n"

        mapping += "**CWE Mapping:**\n"
        mapping += "- CWE-89: SQL Injection\n"
        mapping += "- CWE-564: SQL Injection: Hibernate\n"
        mapping += "- CWE-943: Improper Neutralization of Special Elements in Data Query Logic\n\n"

        return mapping

    def _generate_remediation_recommendations(self, scan_results: Dict) -> str:
        """Generate remediation recommendations"""
        recommendations = "### Immediate Actions Required\n\n"

        vulnerabilities = [v for v in scan_results.get('vulnerabilities', []) if v.get('is_vulnerable')]

        if vulnerabilities:
            recommendations += "1. **Input Validation and Sanitization**\n"
            recommendations += "   - Implement strict input validation for all user inputs\n"
            recommendations += "   - Sanitize special characters (`'`, `\"`, `;`, `--`, etc.)\n"
            recommendations += "   - Use allowlists for expected input formats\n\n"

            recommendations += "2. **Use Parameterized Queries (Prepared Statements)**\n"
            recommendations += "   ```python\n"
            recommendations += "   # Good practice\n"
            recommendations += "   cursor.execute('SELECT * FROM users WHERE id = ?', (user_id,))\n"
            recommendations += "   \n"
            recommendations += "   # Bad practice (vulnerable)\n"
            recommendations += "   cursor.execute(f'SELECT * FROM users WHERE id = {user_id}')\n"
            recommendations += "   ```\n\n"

            recommendations += "3. **Use ORM Frameworks**\n"
            recommendations += "   - Use Django ORM, SQLAlchemy, or similar frameworks\n"
            recommendations += "   - ORMs handle parameterization automatically\n\n"

            recommendations += "4. **Least Privilege Principle**\n"
            recommendations += "   - Database accounts should have minimal required permissions\n"
            recommendations += "   - Avoid using `root` or `admin` accounts for web applications\n\n"

            recommendations += "5. **Web Application Firewall (WAF)**\n"
            recommendations += "   - Deploy WAF to filter malicious requests\n"
            recommendations += "   - Configure rules to block common SQL injection patterns\n\n"

            recommendations += "6. **Error Handling**\n"
            recommendations += "   - Never expose database error messages to users\n"
            recommendations += "   - Log errors securely for debugging\n\n"

            recommendations += "7. **Regular Security Testing**\n"
            recommendations += "   - Perform periodic vulnerability assessments\n"
            recommendations += "   - Implement automated security testing in CI/CD pipeline\n\n"
        else:
            recommendations += "✅ **No immediate actions required.**\n\n"
            recommendations += "Continue following security best practices:\n"
            recommendations += "- Regular security audits\n"
            recommendations += "- Keep dependencies updated\n"
            recommendations += "- Monitor for suspicious activity\n\n"

        return recommendations

    def _generate_detailed_findings(self, scan_results: Dict) -> str:
        """Generate detailed findings for each vulnerability"""
        vulnerabilities = [v for v in scan_results.get('vulnerabilities', []) if v.get('is_vulnerable')]

        if not vulnerabilities:
            return "No detailed findings available.\n\n"

        detailed = ""
        for i, vuln in enumerate(vulnerabilities, 1):
            detailed += f"### Finding #{i}: {vuln.get('vulnerability_type', 'Unknown')}\n\n"
            detailed += f"**Severity:** {vuln.get('severity', 'N/A')}\n\n"
            detailed += f"**Confidence:** {vuln.get('confidence', 'N/A')}\n\n"
            detailed += f"**Parameter:** `{vuln.get('parameter', 'N/A')}`\n\n"
            detailed += f"**Method:** {vuln.get('method', 'N/A')}\n\n"
            detailed += f"**Payload Used:** `{vuln.get('payload', 'N/A')}`\n\n"

            if vuln.get('evidence'):
                detailed += "**Evidence:**\n"
                for evidence in vuln.get('evidence', []):
                    detailed += f"- {evidence}\n"
                detailed += "\n"

            detailed += "---\n\n"

        return detailed

    def generate_json_report(self, scan_results: Dict, output_file: str = None) -> str:
        """
        Generate JSON report

        Args:
            scan_results: Dictionary containing scan results
            output_file: Output filename (optional)

        Returns:
            Path to generated report file
        """
        if not output_file:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_file = f'security_audit_report_{timestamp}.json'

        report_path = os.path.join(self.output_dir, output_file)

        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(scan_results, f, indent=2, default=str)

        return report_path

    def print_summary(self, scan_results: Dict):
        """
        Print summary to console

        Args:
            scan_results: Dictionary containing scan results
        """
        print("\n" + "="*70)
        print("SQL INJECTION SCAN SUMMARY")
        print("="*70)

        vulnerabilities = [v for v in scan_results.get('vulnerabilities', []) if v.get('is_vulnerable')]
        total_vulns = len(vulnerabilities)

        print(f"\nTarget: {scan_results.get('target_url', 'N/A')}")
        print(f"Total Tests: {scan_results.get('total_tests', 0)}")
        print(f"Vulnerabilities Found: {total_vulns}")

        if total_vulns > 0:
            print("\nVulnerabilities by Severity:")
            critical = len([v for v in vulnerabilities if v.get('severity') == 'CRITICAL'])
            high = len([v for v in vulnerabilities if v.get('severity') == 'HIGH'])
            medium = len([v for v in vulnerabilities if v.get('severity') == 'MEDIUM'])
            low = len([v for v in vulnerabilities if v.get('severity') == 'LOW'])

            if critical > 0:
                print(f"  🔴 CRITICAL: {critical}")
            if high > 0:
                print(f"  🟠 HIGH: {high}")
            if medium > 0:
                print(f"  🟡 MEDIUM: {medium}")
            if low > 0:
                print(f"  🟢 LOW: {low}")
        else:
            print("\n✅ No SQL injection vulnerabilities detected!")

        print("\n" + "="*70 + "\n")
